import { Injectable } from '@angular/core';
import { of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class FieldsServiceService {
  constructor() {}

  getFields() {
    return of([
      {
        divider: {
          clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
          contentTypeId: '40e0cb1b57b3b1b7ec34191e942316d5',
          dataType: 'SYSTEM',
          fieldContentTypeProperties: [],
          fieldType: 'Row',
          fieldTypeLabel: 'Row',
          fieldVariables: [],
          fixed: false,
          forceIncludeInApi: false,
          iDate: 1694626929000,
          id: '3212148e35f6cc0151e5a889d494a25f',
          indexed: false,
          listed: false,
          modDate: 1694626939000,
          name: 'fields-0',
          readOnly: false,
          required: false,
          searchable: false,
          sortOrder: 0,
          unique: false,
          variable: 'fields0',
        },
        columns: [
          {
            columnDivider: {
              clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
              contentTypeId: '40e0cb1b57b3b1b7ec34191e942316d5',
              dataType: 'SYSTEM',
              fieldContentTypeProperties: [],
              fieldType: 'Column',
              fieldTypeLabel: 'Column',
              fieldVariables: [],
              fixed: false,
              forceIncludeInApi: false,
              iDate: 1694626929000,
              id: 'fe8da496c69c122889bc13e1f04d548d',
              indexed: false,
              listed: false,
              modDate: 1694626939000,
              name: 'fields-1',
              readOnly: false,
              required: false,
              searchable: false,
              sortOrder: 1,
              unique: false,
              variable: 'fields1',
            },
            fields: [
              {
                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                contentTypeId: '40e0cb1b57b3b1b7ec34191e942316d5',
                dataType: 'TEXT',
                fieldType: 'Text',
                fieldTypeLabel: 'Text',
                fieldVariables: [],
                fixed: false,
                forceIncludeInApi: false,
                iDate: 1694627027000,
                id: 'fa0928f9948dffa0e7d961741aad737e',
                indexed: true,
                listed: true,
                modDate: 1694627027000,
                name: 'Email',
                readOnly: false,
                regexCheck:
                  '^([a-zA-Z0-9]+[a-zA-Z0-9._%+-]*@(?:[a-zA-Z0-9-]+.)+[a-zA-Z]{2,4})$',
                required: true,
                searchable: true,
                sortOrder: 2,
                unique: false,
                variable: 'email',
              },
            ],
          },
          {
            columnDivider: {
              clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
              contentTypeId: '40e0cb1b57b3b1b7ec34191e942316d5',
              dataType: 'SYSTEM',
              fieldContentTypeProperties: [],
              fieldType: 'Column',
              fieldTypeLabel: 'Column',
              fieldVariables: [],
              fixed: false,
              forceIncludeInApi: false,
              iDate: 1694626943000,
              id: 'cde39fbc5e9c233dbead291ef3ae89ae',
              indexed: false,
              listed: false,
              modDate: 1694627027000,
              name: 'fields-2',
              readOnly: false,
              required: false,
              searchable: false,
              sortOrder: 3,
              unique: false,
              variable: 'fields2',
            },
            fields: [
              {
                clazz:
                  'com.dotcms.contenttype.model.field.ImmutableHostFolderField',
                contentTypeId: '40e0cb1b57b3b1b7ec34191e942316d5',
                dataType: 'SYSTEM',
                fieldType: 'Host-Folder',
                fieldTypeLabel: 'Site or Folder',
                fieldVariables: [],
                fixed: false,
                forceIncludeInApi: false,
                hint: 'This is a hint or a helper text',
                iDate: 1694626998000,
                id: 'b09d358d3e471db7ce9836d1954fcf34',
                indexed: true,
                listed: false,
                modDate: 1694627027000,
                name: 'Host Selector',
                readOnly: false,
                required: false,
                searchable: false,
                sortOrder: 4,
                unique: false,
                variable: 'hostSelector',
              },
            ],
          },
        ],
      },
    ]);
  }
}
